name: Build + Test

on: workflow_dispatch

jobs:
  ci:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Aspect Workflows
        uses: aspect-build/workflows-action@5.9.24
              
